import type { NextPageContext } from 'next';
import Head from 'next/head';
import { applyThemeFunc } from '@utils/helpers';
import Navbar from '@molecules/navbar';

function withWrapper(WrappedComponent: any) {
    // TODO : make this a function, params: url, setFunc, toast
    // after the first query, we can store the theme data anywhere
    applyThemeFunc();

    const withThing = (props: any) => {
        return (
            <div className="font-Theme">
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" />
                    <link
                        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700;800&display=swap"
                        rel="stylesheet"
                    />
                </Head>

                <Navbar />
                <WrappedComponent {...props} />
                <footer
                    style={{ marginTop: '100vh' }}
                    className="h-8 w-full  flex items-center justify-center"
                >
                    <p className="font-semibold text-blue-600">footer</p>
                </footer>
            </div>
        );
    };

    withThing.getInitialProps = async ({ req }: NextPageContext) => {
        const host = req?.headers;
        return { host };
    };

    return withThing;
}
export default withWrapper;
